apiVersion: v2
name: mongodb
description: MongoDB StatefulSet for NR ACRFD Comments application
type: application
version: 1.1.0
appVersion: '7.0'
maintainers:
  - name: BC Government
    email: barrett.falk@gov.bc.ca
keywords:
  - mongodb
  - database
  - statefulset
home: https://github.com/bcgov/nr-acrfd-comments
