{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.service.name | default "mongodb" }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  annotations:
    description: Exposes the MongoDB database server
spec:
  type: ClusterIP
  ports:
    - name: mongodb
      port: {{ .Values.mongodb.port | default 27017 }}
      protocol: TCP
      targetPort: mongodb
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
{{- end }}
