name: Deploy MongoDB with Helm

on:
  push:
    branches:
      - main
    paths:
      - "helm/mongodb/**"
      - ".github/workflows/deploy-mongodb.yml"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  deploy-dev:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: MongoDB Deploy (dev)
    uses: ./.github/workflows/.deployer.yml
    with:
      directory: "helm/mongodb"
      environment: "dev"
      triggers: ('helm/mongodb/' '.github/workflows/deploy-mongodb.yml')
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}

  deploy-test:
    name: MongoDB Deploy (test)
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'test'
    uses: ./.github/workflows/.deployer.yml
    with:
      directory: "helm/mongodb"
      environment: "test"
      triggers: ('helm/mongodb/' '.github/workflows/deploy-mongodb.yml')
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}

  deploy-prod:
    name: MongoDB Deploy (prod)
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod'
    uses: ./.github/workflows/.deployer.yml
    with:
      directory: "helm/mongodb"
      environment: "prod"
      triggers: ('helm/mongodb/' '.github/workflows/deploy-mongodb.yml')
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
